src/ocaml/preprocess/lexer_raw.mll

Restore custom `token` function that had been dropped in merge, and update it for the monadic interface used in merlin.

Fix bug in merge

---

import-added-ocaml-source-files.sh
import-ocaml-source.sh

Now, when you run `import-ocaml-source.sh`, you'll be prompted with new files that have been added (in directories that have previously been imported).
This automates an easy-to-forget step of the importing process. (Without this, the importing process just won't bring in new files, and you're left to figure out how to pull in those files.)
Testing:
```
$ ./import-ocaml-source.sh 
From https://github.com/ocaml-flambda/flambda-backend
* branch                main       -> FETCH_HEAD
The script will attempt to import these files added to directories that had previously been imported:
ocaml/parsing/jane_asttypes.mli
ocaml/typing/mode.ml
ocaml/typing/mode.mli
ocaml/typing/uniqueness_analysis.ml
ocaml/typing/uniqueness_analysis.mli
Import new file ocaml/parsing/jane_asttypes.mli? [Y/n] n …
```

Import script pulls in new files added in flambda-backend

---

src/kernel/mconfig.ml

just a little clean up, the flag `-no-auto-include-otherlibs` appeared twice in the whitelist - it should only appear under JS flags.

Remove duplicate ignored flag

---

tests/HACKING.jst.md
tests/dune
tests/merlin-wrapper
tests/ocamlc-wrapper
tests/test-dirs/completion/kind.t/run.t
tests/test-dirs/config/dot-merlin-reader/quoting.t
tests/test-dirs/construct/c-modules.t/run.t
tests/test-dirs/construct/dune
tests/test-dirs/document/dune
tests/test-dirs/document/external-pattern-comments.t
tests/test-dirs/dune
tests/test-dirs/errors/typing-after-parsing.t/run.t
tests/test-dirs/issue1322.t/run.t
tests/test-dirs/locate/dune
tests/test-dirs/locate/functors/dune
tests/test-dirs/locate/ill-typed/dune
tests/test-dirs/locate/module-aliases.t/run.t
tests/test-dirs/occurrences/dune
tests/test-dirs/occurrences/issue1404.t
tests/test-dirs/pp/dune
tests/test-dirs/recovery.t
tests/test-dirs/server-tests/typer-cache/stamps.t/run.t
tests/test-dirs/type-enclosing/dune
tests/test-dirs/typing-recovery.t
tests/test-dirs/with-ppx/dune

Run the merlin-jst test suite.
The main insight: we should use the ocamlc/stdlib corresponding to flambda-backend, not the active opam switch. For now, the cloner of the repo must set environment variables pointing the merlin testsuite at those paths (likely in a local clone of flambda-backend).
This PR then does three other things:
* Accept unconcerning/expected diff in tests
* Skip tests that will take some work to fix (with a comment [1])
* Skip tests that use the system dune, as it will be substantial work to get this to use flambda-backend's compiler (with a comment [2])
Review: Please try building the testsuite locally and let me know if it passes.
[1] `; FIXME: disabled Jane Street tests that are failing internally`
[2] `; Jane Street disabled tests -- they use dune. ; Revisit when …

Fix merlin-jst testsuite

---

tests/merlin-wrapper
tests/ocamlc-wrapper

If you remember to set `MERLIN_TEST_OCAML_PATH` but typo in the value, the tests will run but give weird errors that could be misinterpreted as a bug in your merlin changes.  This adds a check that the relevant files appear to be present at the given location and errors if not, rather than running the tests with a bad value.

Add additional error checking around `MERLIN_TEST_OCAML_PATH`

---

tests/test-dirs/document/module-doc-with-attribute.t

Cf. `tests/test-dirs/document/module-doc.t`, which has the good output.
Problem: requesting the documentation for a module from merlin produces a bad result ("No documentation available") even when the module has a top-level doc comment.
Two ingredients appear to be necessary:
* The user wrote `[@@@ocaml.doc "doc comment here"]` instead of `(** doc comment here *)`. (Or the user ran a ppx preprocessor.)
* The user passes `-bin-annot-cms` to the compiler instead of `-bin-annot`.
Tracked in internal ticket 2135.

Regression test for worse documentation result produced in bin-annot-cms mode

---

src/analysis/stack_or_heap_enclosing.ml
src/analysis/stack_or_heap_enclosing.mli

#44 was rebased on top of #42 / #43 when it was merged. This made the code in #44 stop building because it used the argument-less version of `Mode.Alloc.t`, which now takes a type argument.
This PR fixes that.

Fix #44 to use the new API for `Mode`

---

src/frontend/ocamlmerlin/ocamlmerlin_server.ml

The merlin server writes to pipes received from the merlin client process.  If the read end of those pipes is closed, e.g. because the merlin client process was killed, then when the server writes to the pipe it will generate a SIGPIPE.  This kills the Merlin server. Ignore the SIGPIPE instead of unnecessarily dying.
The fact that you get SIGPIPE when you write to a closed pipe is a classic Unix footgun, and this is the usual resolution.  Another solution is to avoid pipes (in favor of e.g. socketpairs), but we can't do that because we write directly to the file descriptors received from the client.

Ignore SIGPIPE in the Merlin server process

---

src/frontend/ocamlmerlin/ocamlmerlin_server.ml

The Merlin server computes responses in response to client requests.  Sometimes, it can
erroneously write a response from a previous client to a later client, causing multiple
responses to be returned.  I've figured out why this happens and fixed it; it's yet
another wacky collision between the Merlin server's somewhat unusual architecture and the
reality of Unix.
Specifically, the output channels might still have data in their buffers when we get to
the next client.  We call flush_all to try and prevent that, but that can fail with an IO
error, leaving the data in the buffer, and causing it to be written out for the next
client.
Ideally we'd just discard the buffered data for any channel that has an IO error, but I
doubt that's possible with the stdlib channels - I haven't looked in …

Call flush_all twice when closing a client connection

---

src/ocaml/typing/typedecl.ml
src/ocaml/typing/typetexp.ml
tests/test-dirs/errors/issue1704-wrong-message.t

Backport ocaml/merlin#1709 to fix misleading type errors like this:
```ocaml
type t = {
foo : int
bar : baz
}
(*
A type variable is unbound in this type declaration.
In field foo: 'a the variable 'a is unbound
*)
```
@liam923 please merge once you review this.

Backport #1709

---

src/frontend/query_commands.ml
tests/test-dirs/stack-or-heap.t/closures.ml
tests/test-dirs/stack-or-heap.t/run.t
tests/test-dirs/stack-or-heap.t/unfinished.ml

Make allocation analysis definitively state `stack` or `heap` if the program type checks. If it does not, Merlin will sometimes return `could be stack or heap`.

Fix allocation analysis

---

src/kernel/mconfig.ml

The `-gno-upstream-dwarf` is not in the list of flags ignored by Merlin, despite having been in the compiler for the past couple years. I'm surprised this hasn't led to other Merlin issues.

Add `-gno-upstream-dwarf` to list of ignored flags

---

src/analysis/syntax_doc.ml
src/analysis/syntax_doc.mli
src/frontend/ocamlmerlin/new/new_commands.ml
src/frontend/ocamlmerlin/query_json.ml
src/frontend/query_commands.ml
src/frontend/query_protocol.ml
tests/test-dirs/syntax-document/language-extensions.t/run.t

Backport [upstream PR 1706](https://github.com/ocaml/merlin/pull/1706), which adds the `syntax-document` command

Backport 1706

---

src/dot-merlin/dot_merlin_reader.ml
src/dot-protocol/merlin_dot_protocol.ml
src/dot-protocol/merlin_dot_protocol.mli
src/kernel/mconfig.ml
src/kernel/mconfig.mli
src/kernel/mconfig_dot.ml
src/kernel/mconfig_dot.mli
tests/test-dirs/config/dot-merlin-reader/load-config.t
tests/test-dirs/config/dot-merlin-reader/quoting.t

Backport prs [1776](https://github.com/ocaml/merlin/pull/1776) and [1788](https://github.com/ocaml/merlin/pull/1788) from upstream.

Backport `UNIT_NAME` and `WRAPPING_PREFIX` directives

---

src/ocaml/preprocess/lexer_raw.mll
tests/test-dirs/errors/issue1753.t

Backport [PR 1754](https://github.com/ocaml/merlin/pull/1754), which fixes the incorrect handling of quoted strings in comments.

Backport PR 1753

---

src/analysis/destruct.ml
tests/test-dirs/destruct/issue1770.t

Backport [PR #1800 from upstream](https://github.com/ocaml/merlin/pull/1800) , which fixes a bug in destructing functions with optional arguments.

Backport PR #1800

---

src/dot-merlin/dot_merlin_reader.ml
tests/test-dirs/config/dot-merlin-reader/load-config.t
tests/test-dirs/config/dot-merlin-reader/stdlib-config.t

Merlin currently ignores the `STDLIB` directive in `.merlin` files. This PR backports a bugfix to make Merlin use the directive.

Backport 1803 - Fix ignorance of STDLIB directive

---

src/analysis/locate.ml
src/analysis/locate.mli
src/analysis/occurrences.ml
src/ocaml/typing/shape_reduce.ml
src/ocaml/typing/shape_reduce.mli

[PR 2872](https://github.com/ocaml-flambda/flambda-backend/pull/2872) merged some changes to `shape_reduce.ml` into flambda. This PR picks up these changes in Merlin and makes some corresponding changes in `src/analysis`, which are backported from upstream commit [bce24e53e0617579c6a4e2cdc2c35d689ae8da68](https://github.com/ocaml/merlin/commit/bce24e53e0617579c6a4e2cdc2c35d689ae8da68).
Note that `bce24e53e0617579c6a4e2cdc2c35d689ae8da68` also contains some other changes. I believe that these changes are part of a merge from the compiler that are unrelated to the changes to `shape_reduce`.

Backport shape reduce

---

src/analysis/occurrences.ml

There's two logging statements in `occurrences.ml` that trigger an `assert false` due to incorrectly printing a `longident`. This results in some occurrences queries crashing. These two erroneous log statements are both fixed in PR #77, but this PR is meant to act as a quick fix until the changes from #77 are merged and deployed, which may be a couple weeks off.

Fix logging crash

---

src/index-format/index_format.ml

PR #77 missed this change, which causes Merlin to error when loading a cms file due to not recognizing the magic number.

Fix cms magic number issue

---

import-ocaml-source.sh

It's usually a mistake to import directly from the `main` branch of `flambda-backend` -- you should really be importing from a specific tagged version. If you actually want to import `main`, you should need to say so.

Require commit for `import-ocaml-source.sh`

---

.github/workflows/flambda-backend.yml
merlin-lib.opam
src/ocaml/preprocess/menhirLib.ml
src/ocaml/preprocess/menhirLib.mli

In Jane Street's interanl codebase, building with 20231231 is currently problematic. For now, we'll keep this on 20210419 and will upgrade the version in the near future.

Revert menhir to 20210419

---

src/ocaml-index/bin/dune
src/ocaml-index/bin/ocaml_index.ml
src/ocaml-index/lib/index.ml
src/ocaml-index/tests/tests-dirs/cmd.t
src/ocaml-index/tests/tests-dirs/demonstate-cms-deps.t
src/ocaml-index/tests/tests-dirs/index-project.t
src/ocaml-index/tests/tests-dirs/transitive-deps-cms.t

As the title suggests, this PR does two things:
- Add tests that demonstrate ocaml-index working with cms files
- Add a `-H` flag to ocaml-index, which allows passing hidden dependency paths
This is done as 1 PR instead of 2 because the tests rely on the `-H` flag to work properly.

Add ocaml-index tests using cms files and add `-H` flag

---

src/ocaml/typing/typecore.ml
tests/test-dirs/locate/ill-typed/curried-local.t

Fixes error recovery bug for a program like:
```
module List = struct
let map : f:local_ ('a -> 'b) -> 'a list -> 'b list = failwith ""
end
let () = List.map ~invalid_arg:2
```
This bug would prevent users from being able to jump to the definition of List.map in such cases.

Incomplete curried application recovery bugfix

---

tests/test-dirs/destruct/gadt-cross-module.t

PR #38 is an old PR that introduces a hacky workaround to a case that caused Merlin to crash. That bug has since been resolved (presumably due to changes merged from flambda). This PR adds a regression test for the old bug.

Add test for old gadt destruct bug

---

src/ocaml/utils/config.ml
src/ocaml/utils/config.mli

I missed updating the exec magic number in the 5.2.0minus-1 merge (#106).

Remove unused magic numbers

---

src/ocaml/typing/magic_numbers.ml
src/ocaml/utils/config.ml
src/ocaml/utils/config.mli
update-magic-numbers.sh

Add a new script that will bump the magic numbers.
Running this script will:
1. Verify that the git workspace is clean
2. Update the magic numbers in `src/ocaml/utils/config.ml`
3. Add a new entry in `src/ocaml/typing/magic_numbers.ml`
A test run of this script can be done by:
1. Find and replacing `551` with `552` in `upstream/ocaml_flambda/configure`.
2. Commit the above changes.
3. Running `./update-magic-numbers.sh 5.2.0minus-2`
I've performed a few test runs of this script, where:
- All magic numbers changed
- Some magic numbers changed
- No magic numbers changed
- The git workspace is unclean
- There was already an entry in `src/ocaml/typing/magic_numbers.ml`
- The magic numbers in `upstream/ocaml_flambda/configure` are not the expected format
- A new magic number has been added to …

Add script to update magic numbers

---

src/analysis/ast_iterators.ml
src/analysis/index_occurrences.ml
src/analysis/occurrences.ml
tests/test-dirs/let-punning.t/run.t
tests/test-dirs/occurrences/issue827.t/run.t
tests/test-dirs/occurrences/lid-locs.t
tests/test-dirs/occurrences/mod-in-path-2.t
tests/test-dirs/occurrences/mod-in-path-3.t
tests/test-dirs/occurrences/project-wide/prefix.t/run.t
tests/test-dirs/occurrences/project-wide/punning.t/definitions.ml
tests/test-dirs/occurrences/project-wide/punning.t/run.t
tests/test-dirs/occurrences/project-wide/punning.t/usages.ml
tests/test-dirs/occurrences/project-wide/pwo-basic.t
tests/test-dirs/occurrences/project-wide/pwo-canonicalize.t
tests/test-dirs/occurrences/project-wide/pwo-relative.t
tests/test-dirs/occurrences/punning.t/run.t
tests/test-dirs/occurrences/punning.t/test.ml
tests/test-dirs/server-tests/pwo-uid-stability.t

Currently, the occurrences query ignores identifiers if their location is "ghost". This causes issues with finding occurrences in the presence of let punning. Also, this probably produces some undesirable behavior in the presence of ppxs (occurrences within ppx-generated code will be ignored). This PR changes occurrences to instead ignore identifiers whose location is `Location.none`.
This PR also causes the occurrences query to begin filtering occurrences read from an index file. This goes in hand with [this flambda PR](https://github.com/ocaml-flambda/flambda-backend/pull/3137), which causes occurrences in cmt/cms files to not be pre-filtered. Before, flambda also filtered "ghost" locations when producing cmt/cms files. Now, it will do no filtering, leaving the onus on Merlin.
Because …

Ignore `none` locations instead of ghost locations

---

src/sherlodoc/.ocamlformat-ignore
src/sherlodoc/dune
src/sherlodoc/type_parser.ml
src/sherlodoc/type_parser.mli

Backport ocaml/ocaml#1843. This simplifies getting merlin-jst to work as an opam package.
(cherry picked from commit 412c3303afe2a01e90d96717fe08cf1e387148fa)

Backport 1843

---

src/ocaml-index/bin/ocaml_index.ml
src/ocaml-index/tests/tests-dirs/dump-file-stats.t

This PR creates a new sub-command of `ocaml-index` that prints out some meta-data that is contained in index files. I intend to use this command in some tests in our internal codebase because we are currently generating this meta-data incorrectly.

Create `dump-file-stats` command

---

src/frontend/dune
src/ocaml/compression/dune
src/ocaml/compression/ocaml_compression.ml
src/ocaml/typing/dune

Make more compatible with the bleeding-edge-with-extensions opam switch:
* delete the `Compression` module which isn't used
* fix a missing dependency &mdash; I'm not sure why this doesn't affect the local build

Make more compatible with opam

---

src/kernel/mconfig.ml

I've mistakenly neglected adding new flambda parameters to Merlin's list of ignored flags the past few merges. Specifically, the 5.1.1minus-24 merge is the last one where I did not fail to do this. This PR adds all flags that were added to flambda between 5.1.1minus-24 and 5.2.0minus-4.

Add params to ignore

---

src/ocaml/typing/persistent_env.ml

This change was already made in flambda-backend but looks to have been inadvertently dropped during a merge.

Fix handling of instance names in `Persistent_env`

---

src/analysis/typed_hole.ml
src/analysis/typed_hole.mli

This change is backported from an upstream PR: https://github.com/ocaml/merlin/pull/1888. The rest of the changes in that PR are already in merlin-jst.

Move typed_hole from ocaml-lsp

---

tests/test-dirs/parameters.t/run.t

I experienced a flaky failure of the test `tests/test-dirs/parameters.t/run.t`:
```
File "tests/test-dirs/parameters.t/run.t", line 1, characters 0-0:
-tests/test-dirs/parameters.t/run.t
+tests/test-dirs/parameters.t/run.t.corrected
File "tests/test-dirs/parameters.t/run.t", line 325, characters 0-1:
end"
This only compiles if the various ways of getting at [P.t] are equivalent:
$ $OCAMLC -bin-annot-cms -c use_reexported.mli use_reexported.ml -parameter P
This is the function [check_that_types_are_the_same]:
$ query_type use_reexported.ml 1:5 -parameter P
"Reexport.As_alias.t -> Reexport.Included.t -> P.t"
This is a reference to [Reexport.As_alias.create]:
$ multi_query use_reexported.ml 6:30 -parameter P
"unit -> Reexport.As_alias.t"
"Make a thing."
-  {
-    "file": …
```

Stop server before and after parameters test

---

src/analysis/occurrences.ml
src/analysis/occurrences.mli
src/commands/query_json.ml
src/frontend/query_commands.ml
src/frontend/query_protocol.ml
tests/test-dirs/occurrences/basic.t/run.t
tests/test-dirs/occurrences/ext-variant.t
tests/test-dirs/occurrences/issue1398.t/run.t
tests/test-dirs/occurrences/issue1404.t
tests/test-dirs/occurrences/issue1410.t
tests/test-dirs/occurrences/issue827.t/run.t
tests/test-dirs/occurrences/lid-locs.t
tests/test-dirs/occurrences/mod-in-path-2.t
tests/test-dirs/occurrences/mod-in-path-3.t
tests/test-dirs/occurrences/mod-in-path.t
tests/test-dirs/occurrences/occ-types.t
tests/test-dirs/occurrences/pattern.t
tests/test-dirs/occurrences/project-wide/mli-vs-ml.t
tests/test-dirs/occurrences/project-wide/prefix.t/run.t
tests/test-dirs/occurrences/project-wide/pwo-basic.t
tests/test-dirs/occurrences/project-wide/pwo-canonicalize.t
tests/test-dirs/occurrences/project-wide/pwo-relative.t
tests/test-dirs/occurrences/project-wide/stale-index.t
tests/test-dirs/occurrences/project-wide/stale.t
tests/test-dirs/server-tests/pwo-uid-stability.t
tests/test-dirs/unboxed-records.t

When Merlin finds project-wide occurrences, it loads lists of occurrences from index files. Those index files contain metadata about the state of the ml/mli files when the index was generated. This is used as a heuristic to determine if occurrences might be stale (ie, that occurrence was either moved or removed since the index file was generated).
This PR does two things:
1. Fix a bug with Merlin's detection of stale occurrences. Currently, depending on the layout of a repository, Merlin may not line up file paths correctly.
2. Currently, Merlin discards any occurrences it thinks might be stale. This PR changes this so that the stale occurrences are reported, but flagged as being stale.
The net effect for an end user should be nothing - the stale occurrences should still be reported by …

Improve stale occurrences

---

src/analysis/misc_utils.ml
src/analysis/misc_utils.mli
src/analysis/type_enclosing.ml
src/analysis/type_enclosing.mli
src/frontend/query_commands.ml
tests/test-dirs/hidden-deps/dash-h.t
tests/test-dirs/issue1109.t/run.t
tests/test-dirs/misc/load_path.t
tests/test-dirs/type-enclosing/constructors_and_paths.t/run.t
tests/test-dirs/type-enclosing/function-type-error.t
tests/test-dirs/type-enclosing/generic-types.t
tests/test-dirs/type-enclosing/github1003.t/run.t
tests/test-dirs/type-enclosing/issue1477.t
tests/test-dirs/type-enclosing/letop.t/run.t
tests/test-dirs/type-enclosing/mod-type.t/run.t
tests/test-dirs/type-enclosing/objects.t/run.t
tests/test-dirs/type-enclosing/record.t/run.t
tests/test-dirs/type-enclosing/te-413-features.t
tests/test-dirs/type-enclosing/te-modules.t
tests/test-dirs/type-enclosing/types.t/run.t
tests/test-dirs/type-enclosing/underscore-ids.t
tests/test-dirs/type-enclosing/variants.t/run.t

This PR backports upstream pr https://github.com/ocaml/merlin/pull/1864, which fixes some behavior in the `type-enclosing` query. By default, `type-enclosing` returns a list of results, corresponding to nodes enclosing the given position with expanding ranges. For example, if you run `type-enclosing` on `Some (x + 1)` with the cursor on `x`, you will get results corresponding to the expressions `x`, `x + 1`, and `Some (x + 1)`.
Printing types is expensive, so Merlin offers a parameter `-index` to `type-enclosing` that allows you to only request the nth element of that list. Thus, editors can start by requesting only the innermost result and then progressively increase the range as a user requests to.
But the current implementation has a problem. Merlin has some logic to deduplicate …

Backport PR 1864

---

tests/test-dirs/dune

The tests for parameterized libs (`tests/test-dirs/parameters.t`) have been flaky. Presumably this is because they use the merlin server, and multiple tests that use the Merlin server running concurrently can cause unexpected behavior. There is prior art to dealing with this - [dune locks](https://dune.readthedocs.io/en/stable/concepts/locks.html), as seen in `tests/test-dirs/server-tests/dune`. This PR makes the `parameters.t` test take out the `merlin_server` lock.
Locally on my computer, I have been able to reliably trigger a test failure when building and running tests from a clean repo. After this change, I have not triggered the error (n=4), so I am fairly confident that this change fixes the issue.

Fix flaky tests

---

tests/test-dirs/type-enclosing/kinds.t

Add some tests for Merlin printing jkinds in the proper situations. These tests are far from complete, but I wanted to add a regression test for printing types like `type t = u = ...`, and it was easy to add a few more while doing so.

Add tests for printing jkinds

---

src/analysis/overrides.ml
src/analysis/overrides_interval_tree.ml
src/analysis/overrides_interval_tree.mli
tests/test-dirs/overrides.t
tests/test-units/analysis/analysis_test.ml
tests/test-units/analysis/dune
tests/test-units/analysis/overrides_interval_tree_test.ml
tests/test-units/analysis/overrides_interval_tree_test.mli

Implements interval tree and refactors overrides to use this new data structure. The chosen interval tree design is based off of [this description](https://en.wikipedia.org/wiki/Interval_tree#Centered_interval_tree). 
Added unit tests for invalid inputs and common happy path cases. 
Testing story can possibly be improved with more edge case testing.

merlin overrides use interval tree instead of list

---

src/analysis/outline.ml
src/analysis/outline.mli
src/commands/new_commands.ml
src/commands/query_json.ml
src/frontend/ocamlmerlin/old/old_IO.ml
src/frontend/query_commands.ml
src/frontend/query_protocol.ml
tests/test-dirs/outline.t/run.t

The title is fairly self-explanatory. This is to enable the LSP to use Merlin's outline query directly rather than using an ad-hoc implementation.

Add option to not print types when getting the outline

---

.github/workflows/update-flake-lock.yml

This PR adds a new GitHub action that will open a PR if the `flake.lock` file is out of sync with the `flake.nix` file. See https://github.com/marketplace/actions/update-nix-flake-lock.

Add update-flake-lock workflow
